version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      - ..:/workspace:cached
    
    command: sleep infinity
    
    network_mode: service:db
    
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: "True"
      DB_TYPE: sqlite

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
    environment:
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot_dev
      POSTGRES_DB: chatbot_dev

volumes:
  postgres-data:

